motors:
  ILM25x08:
    poles:          14          # 7 pole-pairs
    torque_nom_Nm:  0.063
    torque_peak_Nm: 0.204
    kT_Nm_per_A:    0.0147
    stator_OD_mm:   25
    rotor_ID_mm:    11.6
    stator_len_mm:  15.2
    rotor_len_mm:   9.7
    rated_current_A: 4.3
    rated_voltage_V: 24
  ILM50x14:
    poles:          20          # 10 pole-pairs
    torque_nom_Nm:  0.54
    torque_peak_Nm: 1.75
    kT_Nm_per_A:    0.103
    stator_OD_mm:   50
    rotor_ID_mm:    30
    stator_len_mm:  22.6
    rotor_len_mm:   16.1
    rated_current_A: 5.3
    rated_voltage_V: 48

geometry_errors:
  static_ecc:   [0.00, 0.02, 0.05]   # mm
  dynamic_ecc:  [0.00, 0.02]         # mm
  tilt_deg:     [0.0, 0.2, 0.5]      # °
  centering_dx: [0.00, 0.05]         # mm

encoder_bits: 14            # 16384 counts/rev
hil_freq_kHz: [2, 5]        # sampling rates
step_deg:     1.0           # electrical sweep step
controller:   ["FOC", "SixStep"]
